import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import UserProvider from "@/wrappers/UserWrapper";
import { RequestProvider } from "@/wrappers/RequestWrapper";
import ResponseWrapper from "@/wrappers/ResponseWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Post Man",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <RequestProvider>
               <ResponseWrapper>
                  {children}
               </ResponseWrapper>
            </RequestProvider>
        </UserProvider>
      </body>
    </html>
  );
}
